import { PrefecturePopulationData } from "@/schemas/resas-api/population";
import { PrefectureCheckbox } from "@/components/PrefectureCheckbox";
import { AreaChart } from "@/components/AreaChart";
import { API_ENDPOINT } from "@/configs/resas-api";
import { getPrefectures } from "@/apis/resas-api";

import { PrefectureCheckboxList } from "@/components/PrefectureCheckboxList";
import { Section } from "@/components/Section";
import { Layout } from "@/components/Layout";
import { Header } from "@/components/Header";
import { useState } from "react";
import Head from "next/head";
import useSWR from "swr";

export default function Home() {
  const { data: prefectures } = useSWR(
    API_ENDPOINT.PREFECTURES,
    getPrefectures
  );

  const [prefecturePopulationData, setPrefecturePopulationData] = useState<
    PrefecturePopulationData[]
  >([]);

  const [categories, setCategories] = useState<string[]>([]);

  return (
    <>
      <Head>
        <title>都道府県別 総人口推移グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Layout>
        <Section heading="都道府県">
          <PrefectureCheckboxList>
            {prefectures?.map((prefecture) => (
              <PrefectureCheckbox
                prefecture={prefecture}
                setPrefecturePopulationData={setPrefecturePopulationData}
                setCategories={setCategories}
                key={prefecture.prefCode}
              />
            ))}
          </PrefectureCheckboxList>
        </Section>

        <Section heading="人口数">
          <AreaChart data={prefecturePopulationData} categories={categories} />
        </Section>
      </Layout>
    </>
  );
}
